# =============================================================================
# Role: K3s - Handlers
# =============================================================================

---
- name: Restart K3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted

- name: Restart K3s agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
