# =============================================================================
# Role: Users - Handlers
# =============================================================================

---
- name: Reload SSH
  systemd:
    name: sshd
    state: reloaded
